### PR TITLE
Stream reader encoding

### PR DESCRIPTION
**Pull request by nhennebe67**

### CODE REVIEW

**Comment by nhennebe67** [comment]
Any news on approving this PR?

Thank you,

Nico

**Comment by David-Noble-at-work** [comment]
The XmlReader should respect the character encoding specified in the XML Prolog that Splunk sends:

    <?xml version="1.0" encoding="UTF-8"?>
    <?xml-stylesheet type="text/xml" href="/static/atom.xsl"?>

Splunk should always be specifying UTF-8 character encoding and the XmlReader should complain, if the response data includes characters that don't conform to the UTF-8 character encoding. 

Do you have an example where this is not the case?

**Comment by nhennebe67** [comment]
Yes, I do have an example of illegal characters that is returned by Splunk in a response that is supposed to be utf-8. Note that as a consultant in the field, I do not have any control over the Splunk instance I connect to, the Splunk version or anything on the server side. All I have is the API. I use the .Net Client when this is what the customer requires. Take a look at the file attached, line 14: an xml validator would complain about it, just like XmlReader. The solution I am proposing in this Pull Request works around the issue, because you can override the parsing encoding with something that does not break XmlReader. It's critical for me to have that option and I think it will be useful for the community. I encounter this issue a lot in the field. Do you have an alternative solution? In the meantime I am using my own fork of the project, but I would rather use the official distribution from NuGet.

Thank you

[splunk_bad_xml.zip](https://github.com/splunk/splunk-sdk-csharp-pcl/files/87888/splunk_bad_xml.zip)

**Comment by nhennebe67** [comment]
Any news on this PR?

**Comment by David-Noble-at-work** [comment]
The example you've provided indicates there's a bug in Splunk which should never be sending invalid the invalid UTF-8 character 0xFF, 0xFF. I might like to address that issue as well. What version of Splunk is sending the invalid UTF-8 character? What encoding are you using to work around it?

**Comment by nhennebe67** [comment]
Most recently I have seen bad characters returned by a Splunk 6.2.4.
I use ISO-8859-9 as encoding override to work around it.

**Comment by David-Noble-at-work** [comment]
There's a window of opportuninity to address this issue in the next maintenance release of Splunk 6.2.
- Can you share the query you're executing?
- Can you send some additional samples of problematic results?
ISO-8859-9 is a Turkish character set. 
- Are you expecting Turkish characters? The 0xFF, 0xFF that Splunk is returning maps to "ÿÿ" in ISO-8859-9. Is that the value you're expecting?

**Comment by nhennebe67** [comment]
I choose Turkish as a work around, other ISO-* encoding would work too. I was not expecting Turkish. 0xFF looks like crappy data in my case, and I discard these values downstream in my processing. I just need those characters not to crash my utility.

I do not have other samples with 0xFF handy.
I queried an index containing Windows Security Log data from a WMI connector.

`(EventCode=4624 OR EventCode=4625 OR EventCode=4648 OR EventCode=528 OR EventCode=529 OR EventCode=530 OR EventCode=532 OR EventCode=533 OR EventCode=534 OR EventCode=535 OR EventCode=539 OR EventCode=540 OR EventCode=682) AND NOT (Account_Name="*$" OR User_Name="*$" OR Logon_Account="*$") AND sourcetype="*WinEventLog:Security*"'
			,'eval deviceReceiptTime = round(_time,0) | eval eventId = index + "_" + _cd + "_" + splunk_server + "_" + deviceReceiptTime
			| eval Source_Network_Address = case(EventCode=4624 OR EventCode=4625 OR EventCode=528 OR EventCode=529 OR EventCode=530 OR EventCode=532 OR EventCode=533 OR EventCode=534 OR EventCode=535 OR EventCode=539 OR EventCode=540, Source_Network_Address, EventCode=4648, Network_Address, EventCode=682, Client_Name)
			| eval Workstation_Name = case(EventCode=4624 OR EventCode=4625 OR EventCode=528 OR EventCode=529 OR EventCode=530 OR EventCode=532 OR EventCode=533 OR EventCode=534 OR EventCode=535 OR EventCode=539 OR EventCode=540, Workstation_Name, EventCode=682, Client_Name)
			| eval ComputerName = case(EventCode=4624 OR EventCode=4625 OR EventCode=528 OR EventCode=529 OR EventCode=530 OR EventCode=532 OR EventCode=534 OR EventCode=535 OR EventCode=539 OR EventCode=540 OR EventCode=682, ComputerName, EventCode=4648, Target_Server_Name)
			| eval Account_Name = case(EventCode=4624 OR EventCode=4625 OR EventCode=4648,mvindex(Account_Name,1), EventCode=528 OR EventCode=529 OR EventCode=530 OR EventCode=532 OR EventCode=533 OR EventCode=534 OR EventCode=535 OR EventCode=539 OR EventCode=540 OR EventCode=682, User_Name)
			| eval Account_Domain = case(EventCode=4624 OR EventCode=4625 OR EventCode=4648,mvindex(Account_Domain,1), EventCode=528 OR EventCode=529 OR EventCode=530 OR EventCode=532 OR EventCode=533 OR EventCode=534 OR EventCode=535 OR EventCode=539 OR EventCode=540 OR EventCode=682, Domain)
			| table eventId, deviceReceiptTime,EventCode,Logon_Type,Account_Domain,Account_Name,Workstation_Name,Source_Network_Address,Workstation_Name,ComputerName,Type`

**Pull request closed without merging**
